#ifndef TRIVIA_HPP
#define TRIVIA_HPP

//THESE FUNCTIONS GENERATE A RANDOM TRIVIA QUESTION FOR THE PLAYER TO ANSWER.
//IF THE PLAYER ANSWERS CORRECTLY, THEY WILL SUCCESSFULLY DODGE THE ATTACK. IF THEY ANSWER INCORRECTLY, THEY WILL TAKE DAMAGE.
//AS THE PLAYER PROGRESSES THROUGH THE GAUNTLET, THEY WILL FACE HARDER QUESTIONS.
int randTrivia1();
int randTrivia2();
int randTrivia3();

#endif